name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v2
        with:
          tree-sitter-ref: v0.26.8

      - name: Run tests
        uses: tree-sitter/parser-test-action@v3
        with:
          test-rust: true
          test-node: false # https://github.com/tree-sitter/node-tree-sitter/issues/268
          test-python: true
          test-go: true
